server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb+srv://aburgoss:aburgoss@cluster0.ibhoc.mongodb.net/ClientsDB?retryWrites=true&w=majority

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
