server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://aburgoss:aburgoss@cluster0.ibhoc.mongodb.net/RegisterProductClientDB?retryWrites=true&w=majority

eureka:
  client: 
    serviceUrl:
      defaultZone: http://192.168.1.3:8761/eureka/
  instance:
    id: ${spring.application.name}:${spring.application.instance_id}:${random.value}
    
