server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:123456.@ms-transaction.aghqo.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
