server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:123456.@ms-transaction.aghqo.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.3:8761/eureka/
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      id: ${spring.application.name}:${spring.application.instance_id}:${random.value}
