4 lines (12 sloc)  341 Bytes
   
server:
  port: 8085

spring:
  data:
    mongodb:
      uri: mongodb+srv://aburgoss:aburgoss@cluster0.ibhoc.mongodb.net/WalletDB?retryWrites=true&w=majority

eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    id: ${spring.application.name}:${spring.application.instance_id}:${random.value}
